package nonsquarematrisreverse;

import javax.swing.JTextArea;

public class Goster extends javax.swing.JFrame {
    
    JTextArea arrTextArea[] = new JTextArea[5];

    
    public void matrisYazdir(double[][] matris, int i) {
        String text = "";
        for(int j=0;j<matris.length;j++){
            for(int k=0;k<matris[j].length;k++){
                text += String.format( "%.2f",matris[j][k]) + "       ";
            }
            text += "\n\n";
        }
        arrTextArea[i].setRows(matris.length);
        arrTextArea[i].setText(text);
    }
    
    public Goster() {
        initComponents();
    }
    
    public Goster(double[][] matris, double[][] matrisTranspoz, double[][] firstMult, double[][] multTers, double[][] son, int det, int carpimSayisi, int toplamaSayisi) {
        initComponents();
        
        arrTextArea[0] = jMatris;  arrTextArea[1] = jMatrisTranspoz;  arrTextArea[2] = jFirstMult;
        arrTextArea[3] = jMultTers;  arrTextArea[4] = jSon;
        matrisYazdir(matris, 0); matrisYazdir(matrisTranspoz, 1);  matrisYazdir(firstMult, 2);
        matrisYazdir(multTers, 3);  matrisYazdir(son, 4);
        if(det == 0){
            firstMultLabel.setText("A*A(T)");
            multTersLabel.setText("( A * A(T) )^(-1)");
            sonLabel.setText("A(T)*( ( A * A(T) )^(-1) )");
        }
        carpimLabel.setText("Çarpım Sayısı = " + carpimSayisi);
        toplamaLabel.setText("Toplama Sayısı = " + toplamaSayisi);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jMatris = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jFirstMult = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jMatrisTranspoz = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jSon = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jMultTers = new javax.swing.JTextArea();
        transozLabel = new javax.swing.JLabel();
        matrisLabel = new javax.swing.JLabel();
        firstMultLabel = new javax.swing.JLabel();
        sonLabel = new javax.swing.JLabel();
        multTersLabel = new javax.swing.JLabel();
        carpimLabel = new javax.swing.JLabel();
        toplamaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMatris.setEditable(false);
        jMatris.setColumns(20);
        jMatris.setRows(5);
        jScrollPane1.setViewportView(jMatris);

        jFirstMult.setEditable(false);
        jFirstMult.setColumns(20);
        jFirstMult.setRows(5);
        jScrollPane2.setViewportView(jFirstMult);

        jMatrisTranspoz.setEditable(false);
        jMatrisTranspoz.setColumns(20);
        jMatrisTranspoz.setRows(5);
        jScrollPane3.setViewportView(jMatrisTranspoz);

        jSon.setEditable(false);
        jSon.setColumns(20);
        jSon.setRows(5);
        jScrollPane4.setViewportView(jSon);

        jMultTers.setEditable(false);
        jMultTers.setColumns(20);
        jMultTers.setRows(5);
        jScrollPane5.setViewportView(jMultTers);

        transozLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        transozLabel.setText("A(T)");

        matrisLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        matrisLabel.setText("A");

        firstMultLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        firstMultLabel.setText("A(T) * A");

        sonLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sonLabel.setText("( ( A(T) * A )^(-1) ) * A(T)");

        multTersLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        multTersLabel.setText("( A(T) * A )^(-1)");

        carpimLabel.setText("carpim");

        toplamaLabel.setText("toplama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(matrisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transozLabel)
                .addGap(206, 206, 206)
                .addComponent(firstMultLabel)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toplamaLabel)
                                    .addComponent(carpimLabel)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(multTersLabel)
                        .addGap(90, 90, 90)
                        .addComponent(sonLabel)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstMultLabel)
                    .addComponent(transozLabel)
                    .addComponent(matrisLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multTersLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sonLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(carpimLabel)
                        .addGap(28, 28, 28)
                        .addComponent(toplamaLabel)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Goster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Goster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Goster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Goster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Goster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carpimLabel;
    private javax.swing.JLabel firstMultLabel;
    private javax.swing.JTextArea jFirstMult;
    private javax.swing.JTextArea jMatris;
    private javax.swing.JTextArea jMatrisTranspoz;
    private javax.swing.JTextArea jMultTers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jSon;
    private javax.swing.JLabel matrisLabel;
    private javax.swing.JLabel multTersLabel;
    private javax.swing.JLabel sonLabel;
    private javax.swing.JLabel toplamaLabel;
    private javax.swing.JLabel transozLabel;
    // End of variables declaration//GEN-END:variables
}
